// Generated by scripts/build-detections.js -- do not edit by hand.
// Cortex XSIAM / XDR XQL -- Steam credential phishing domain
// ATT&CK T1566.002, T1656
//
// Prerequisite: load detections/lookups/steam-lookalike-domains.csv as the
// lookup dataset `steam_lookalike_domains` (fields: host, signal). Repoint the
// dataset and field names at whichever source carries your web traffic.

dataset = panw_ngfw_url_logs
| alter host = lowercase(url_domain), uri = lowercase(url_path)
| filter host != null
// official Steam domains short-circuit, exactly as the scorer allowlists them
| filter not (host = "steamcommunity.com" or host ~= "\.steamcommunity\.com$" or host = "steamgames.com" or host ~= "\.steamgames\.com$" or host = "steampowered.com" or host ~= "\.steampowered\.com$" or host = "steamstatic.com" or host ~= "\.steamstatic\.com$" or host = "valvesoftware.com" or host ~= "\.valvesoftware\.com$")
| join type = left conflict_strategy = both (
    dataset = steam_lookalike_domains
    | fields host as lookalike_host, signal as lookalike_signal
  ) as lk lk.lookalike_host = host
| alter signal = if(
    lookalike_host != null, "lookalike_domain",
    host ~= "(steamcommunity\.com|steamgames\.com|steampowered\.com|steamstatic\.com|valvesoftware\.com)\.", "embedded_official_host",
    host ~= "(steamcommunity|steamgames|steampowered|steamstatic|valvesoftware)", "embedded_official_label",
    null)
| filter signal != null
| comp count() as hits, min(_time) as first_seen, max(_time) as last_seen by host, source_ip, signal
| alter technique = "T1566.002"
| sort desc hits
